import './globals.css'
import './styles.css'
import type { Metadata } from 'next'
import Providers from './Providers';
import ReduxProviders from '@/redux/providers';
import Navbar from '@/components/Navbar';
import Sidebar from '@/components/Sidebar';
import 'react-toastify/dist/ReactToastify.css';
import { ToastContainer } from 'react-toastify';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
        <head>
        </head>
        <body  >
        <Providers>
          <ReduxProviders>
            
                <Navbar/>
                <Sidebar/>
                <div className="p-4 sm:ml-64">
                    <div className="p-4 border-2 border-gray-200 border-dashed rounded-lg dark:border-gray-700 mt-14">
                        
                                {children}
                          
                    </div>
                </div>
                <ToastContainer />
          </ReduxProviders>
        </Providers>
        <script defer src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.8.0/flowbite.min.js"></script>
        </body>
    </html>
  )
}
