import './globals.css'
import type { Metadata } from 'next'
import Providers from './Providers';
import Navbar from '@/components/Navbar';
import Sidebar from '@/components/Sidebar';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
        <head>
            <link href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.8.0/flowbite.min.css" rel="stylesheet" />
        </head>
        <body suppressHydrationWarning={true} >
        <Providers>
            <Navbar/>
            <Sidebar/>
            <div className="p-4 sm:ml-64">
                <div className="p-4 border-2 border-gray-200 border-dashed rounded-lg dark:border-gray-700 mt-14">
                    <div className="grid grid-cols-1 gap-4 ">
                        <div className="flex items-center justify-center rounded bg-gray-50 dark:bg-gray-800">
                            {children}
                        </div>
                    </div>
                </div>
            </div>
        </Providers>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.8.0/flowbite.min.js"></script>
        </body>
    </html>
  )
}
